"""roles and internal notification contacts

Revision ID: a8a75b0fed73
Revises: ad75e6d45488
Create Date: 2026-08-17 00:53:09.872006+00:00

Роль пользователя панели и его Telegram для внутренних уведомлений.

Все четыре колонки NOT NULL, поэтому идут с server_default — иначе миграция
падает на таблице с людьми: «column ... contains null values».

Существующие пользователи становятся владельцами, а не администраторами. До
этой ревизии роли не было и каждый вошедший распоряжался подключениями и
ключами; выкатить миграцию, которая молча отбирает доступ у работающих людей,
хуже, чем оставить лишние права до явного решения владельца. Умолчание `admin`
действует только для тех, кого заведут после.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a8a75b0fed73'
down_revision = 'ad75e6d45488'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('role', sa.String(length=16),
                                      nullable=False, server_default='admin'))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=40),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('notify_new_booking', sa.Boolean(),
                                      nullable=False, server_default=sa.true()))
        batch_op.create_index(batch_op.f('ix_admin_users_role'), ['role'], unique=False)

    # Кто уже работал в панели — владелец: роли не было, и доступ у всех был
    # полный. Отбирать его миграцией нельзя, это решение владельца.
    op.execute("UPDATE admin_users SET role = 'owner'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_role'))
        batch_op.drop_column('notify_new_booking')
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
